var fs = require('fs');
var http = require('http');

// creating a server which will return a response...
var server = http.createServer(function(req, res) {
  // req.url returns the path after the ip address and the port number...
  console.log('The request path is: ' + req.url);
  // setting the response header...
  res.writeHead(200, {'Content-Type': 'text/plain'});
  // reading content chunk by chunk from readme.txt...
  var myReadStream = fs.createReadStream(__dirname + '/readme.txt', 'utf8');
  // As response is a writable stream. so, we can pipe the chunk data read from
  // readme.txt to the response as we need to show it to client...
  myReadStream.pipe(res);
});

// now, if we request to 127.0.0.1:3000 we will get the content of readme.txt...
server.listen(3000, '127.0.0.1');
console.log('listening to port 3000:');
